apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dy9bzh44c-python
  janus-idp.io/tekton: dy9bzh44c-python
  backstage.io/kubernetes-id: dy9bzh44c-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dy9bzh44c-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
